name: deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm install
      - name: Deploy Build
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u "${USER_NAME} ${USER_EMAIL}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_NAME: DaiF1
